### ISSUE TITLE
Assistance in development

### ISSUE THREAD

**Issue by hikarosato** [Eisenmonoxid/S7Patcher#1]
Hi, I'm really glad you're working on another unofficial patch for Settlers 7, I'd like to offer my help in testing it since I have the History edition from Steam.
Here is unpacked steamless exe:
[Settlers7R-exe_STEAMLESS.zip](https://github.com/user-attachments/files/18052246/Settlers7R-exe_STEAMLESS.zip)

My Discord:   **.hikaro**

**Comment by Eisenmonoxid** [comment]
Hey,
Thanks for your offer. The S7Patcher application currently supports unlocking the DLC that became unavailable when the servers for the original release of the game were shut down. These features should already be available in the History Edition of the game, so it does not really make sense to implement History Edition support right now.

However, should i ever plan on doing more features for Settlers 7, i will come back to you. I can't promise anything however, since i'm currently busy with other games.
If you want to extend the application with features yourself, feel free to fork and create a pull request.

Regards,
Eisenmonoxid

**Comment by hikarosato** [comment]
Sure, at first, you can add LAA flag because Settlers 7 is still 32-bit exe. And I got 2 crashes with dumps:
[Settlers7_AGame_2024-11-25_02-01-58.dmp](https://github.com/user-attachments/files/18054090/Settlers7_AGame_2024-11-25_02-01-58.dmp)
[Settlers7_AGame_2024-12-08_09-23-41.dmp](https://github.com/user-attachments/files/18054092/Settlers7_AGame_2024-12-08_09-23-41.dmp)
If you have time, can you check these dumps, maybe there is some game bug, like Settlers 6 had with entertainer and it can be fixed.
