### ISSUE TITLE
Can't get pass the profile manager screen

### ISSUE THREAD

**Issue by Mikomanus** [Eisenmonoxid/S7Patcher#2]
Hi. I got a steam gold edition of the game. After installing the patch, the game launches and it goes right into the profile manager (no intro, no ubisoft logo, no music), where i am suppose to choose name and other info. After everything is set i am not able to click the continue button. I mean i am able to click it but it does not do anything. So i am stucked at that screen. With old executable the game works just fine but the DLC is not available.

**Comment by Eisenmonoxid** [comment]
Yes, i see the problem - Documents\Settlers7\Profiles.xml has to be already created when the game was still online, otherwise it will not work. I will take a look at it, and try to fix it. Can't give a time however.

For the time being, if you are able to work with a HexEditor (e.g. HxD), you could modify the Settlers7R.exe yourself by editing the following addresses:

```
- Edited out, use the application instead.
```

You won't have features like the castle forge or the profile system then, but the DLC maps and UPlay rewards should still work fine.

Regards,
Eisenmonoxid

**Comment by Mikomanus** [comment]
> Yes, i see the problem - Documents\Settlers7\Profiles.xml has to be already created when the game was still online, otherwise it will not work. I will take a look at it, and try to fix it. Can't give a time however.
> 
> For the time being, if you are able to work with a HexEditor (e.g. HxD), you could modify the Settlers7R.exe yourself by editing the following addresses:
> 
> ```
> - Edited out, use the application instead.
> ```
> 
> You won't have features like the castle forge or the profile system then, but the DLC maps and UPlay rewards should still work fine.
> 
> Regards, Eisenmonoxid

Amazing! you are the best. It works. I had to do it from the original - none patched version. But now i can continue with my xmass adventure thanks to you :) Cheers.

**Comment by Eisenmonoxid** [comment]
Great to hear that it worked! I also fixed the problem in the application and pushed a new release, so if you want access to the castle forge and the profile system, you could try again (with an unpatched executable).

**Comment by Mikomanus** [comment]
Working like a charm. thank you once again :)
